Add uncommitted events to the class definition
Prior to this change, this started to fail on new version of mypy
(1.5.0) because the name was not in the `__slots__` created by `attrs`:

    error: Trying to assign name "uncommitted_events" that is not in "__slots__" of type "testing.application.unit_of_work.MemoryCommitter"  [misc]

This change adds the field so it will be.